services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-admin@example.com}'
        PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-password}'
    ports:
      - "${FORWARD_PGADMIN_PORT:-5050}:80"
    depends_on:
      - pgsql
    networks:
      - sail
    volumes:
      - sail-pgadmin:/var/lib/pgadmin
  # redis-ui:
  #   image: redis/redisinsight
  #   ports:
  #     - "${FORWARD_REDIS_UI_PORT:-5540}:5540"
  #   networks:
  #     - sail
  #   depends_on:
  #     - redis
  #   volumes:
  #     - sail-redis-ui:/data
volumes:
  sail-pgadmin:
    driver: local
  # sail-redis-ui:
  #   driver: local
