services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD: '${PGADMIN_CONFIG_MASTER_PASSWORD}'
    ports:
      - "${FORWARD_PGADMIN_PORT:-5050}:80"
    depends_on:
      - pgsql
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - app_net

volumes:
  pgadmin-data:
    driver: local
